version: "2.3"
services:
  tf2_12:
    build: .
    network_mode: host
    ipc: host
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../:/home/user/Documents/tensorflow_ws
    privileged: true
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    working_dir: /home/user/Documents/tensorflow_ws