FROM nvcr.io/nvidia/tensorflow:23.07-tf2-py3
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
      protobuf-compiler
RUN apt-get install python3-pip -y
RUN pip3 install opencv-python
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
